version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      - pip install uv
    post_install:
      - uv pip install -e ".[docs,examples]"

sphinx:
  configuration: docs/conf.py
