site_name: Vessim
site_url: !ENV READTHEDOCS_CANONICAL_URL
repo_url: https://github.com/dos-group/vessim

extra_javascript:
  - javascripts/mathjax.js
  - javascripts/readthedocs.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Overview: index.md
  - Getting Started: getting_started.md
  - Concepts:
    - Signals and Datasets: concepts/signals.md
    - Dispatchables and Dispatch Policies: concepts/dispatchables.md
    - Controllers: concepts/controllers.md
    - Software-in-the-Loop: concepts/sil.md
  - API Reference:
    - Environment: api_reference/environment.md
    - Microgrid: api_reference/microgrid.md
    - Actor: api_reference/actor.md
    - Signal: api_reference/signal.md
    - Dispatchable: api_reference/dispatchable.md
    - Dispatch Policy: api_reference/dispatch_policy.md
    - Controller: api_reference/controller.md
    - CLI: api_reference/cli.md
  - Publications: publications.md
  - About: about.md

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo_white.svg
  favicon: assets/favicon.svg
  features:
    - content.code.copy
    - content.code.annotate
  palette:
    - scheme: default
      primary: teal
      accent: teal

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            show_root_full_path: false
            show_signature: false
            show_symbol_type_heading: true
            show_labels: true
            members_order: source
            filters:
              - "!^_"

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true