#!/bin/bash

cd ..
username=$(terraform output -raw gcp_user_name)
address=$(terraform output -raw external_ip)
mkdir out
scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i .ssh/google_compute_engine $username@$address:/home/$username/$1 out/
