{
 "title": "Energy sources dashboard",
 "time": { "from": "2022-06-15T00:00:00.000Z", "to": "2022-07-04T23:55:00.000Z" },
 "templating": {
  "list": [
   { "name": "microgrid", "label": "Microgrid", "query": "datacenter,office" }
  ]
 },
 "panels": [
  {
   "title": "Zusammensetzung Energieproduktion",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "// 1. Basis-Datenquelle\r\ndata = from(bucket: \"vessim_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vessim\" and r.microgrid == \"$microgrid\")\r\n\r\n// 2. Solar + Wind summieren\r\nsolar_wind_sum = data\r\n  |> filter(fn: (r) =>\r\n    r._field == \"power_solar_panel\" or\r\n    r._field == \"power_wind_turbine\"\r\n  )\r\n  |> group(columns: [\"_field\"])\r\n  |> sum(column: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _field:\r\n        if r._field == \"power_solar_panel\" then \"Solar-Gesamtenergie\"\r\n        else \"Wind-Gesamtenergie\"\r\n  }))\r\n  |> rename(columns: {_value: \"\"})\r\n  |> keep(columns: [\"_field\", \"\"])\r\n\r\n// 3. Netzbezug (nur negative Werte, invertieren)\r\np_grid_imported = data\r\n  |> filter(fn: (r) => r._field == \"p_grid\")\r\n  |> filter(fn: (r) => r._value < 0)\r\n  |> sum(column: \"_value\")\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: r._value * -1.0,\r\n      _field: \"Bezug-Gesamtenergie\"\r\n  }))\r\n    |> rename(columns: {_value: \"\"})\r\n    |> keep(columns: [\"_field\", \"\"])\r\n\r\n// 4. Zusammenführen\r\nunion(tables: [solar_wind_sum, p_grid_imported])\r\n"
    }
   ]
  },
  {
   "title": "Solar erzeugung pro Tag",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 19, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "targets": [
    {
     "query": "from(bucket: \"vessim_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"vessim\" and\n    r._field == \"power_solar_panel\" and\n r.microgrid == \"$microgrid\"\n  )\n  |> aggregateWindow(every: 1d, fn: mean, createEmpty: false)\n  |> map(fn: (r) => ({ r with _value: r._value * 24.0 / 1000.0 }))\n  |> rename(columns: {_value: \"avg_power_solar\"})\n  "
    }
   ]
  },
  {
   "title": "Windenergie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"vessim_bucket\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"vessim\" and\r\n    r._field == \"power_wind_turbine\" and\r\n    r.microgrid == \"$microgrid\"\r\n  )"
    }
   ]
  },
  {
   "title": "Stromnetznutzung ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"vessim_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"vessim\" and\n    r._field == \"p_grid\" and\n    r.microgrid == \"$microgrid\"\n  )"
    }
   ]
  },
  {
   "title": "Solarenergie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "query": "from(bucket: \"vessim_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"vessim\" and\n    r._field == \"power_solar_panel\" and\n    r.microgrid == \"$microgrid\"\n  )"
    }
   ]
  },
  {
   "title": "Ladestand Batterie",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "from(bucket: \"vessim_bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"vessim\" and\n    r._field == \"soc\" and\n    r.microgrid == \"$microgrid\"\n  )"
    }
   ]
  }
 ]
}