#!/bin/bash

cd ..
username="ubuntu"
address=$(terraform output -raw public_ip)
mkdir out
scp -r -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i .ssh/aws_ec2 $username@$address:/home/$username/$1 out/
