#!/bin/bash
for name in actor controller cosim policy signal storage
do
    echo "vessim.$name" > $name.rst
    len=$((${#name} + 7))  # Calculate length of "vessim." + $name
    printf "%${len}s\n" | tr ' ' '=' >> $name.rst
    echo ".. automodule:: vessim.$name" >> $name.rst
    echo "   :members:" >> $name.rst
    echo "   :undoc-members:" >> $name.rst
    echo "   :show-inheritance:" >> $name.rst
done
