name: Build

on:
  pull_request:
    branches:
    - main

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.13]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv and set python version to ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    # build package
    - name: Build package
      run: uv build

    # install package
    - name: Install package
      run: uv pip install dist/*.tar.gz

    # Install dependencies needed for notebook execution
    - name: Install notebook dependencies
      run: uv pip install -e ".[examples]"

    # Execute example notebooks to verify that no errors are thrown
    - name: Run Jupyter Notebooks
      run: |
        notebooks=("examples/signal_example.ipynb" "examples/basic_example.ipynb" "examples/controller_example.ipynb" "examples/stranger_sims_example.ipynb")
        for notebook in "${notebooks[@]}"; do
          jupyter nbconvert --to notebook --execute "$notebook"
        done
