name: Tests

on: 
  push:

jobs:
  linting-and-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.13]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv and set python version to ${{ matrix.python-version }}
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ matrix.python-version }}
        enable-cache: true

    - name: Install hatch-vcs plugin
      run: uv pip install hatch-vcs

    - name: Install dependencies
      run: uv pip install -e ".[dev,sil]"

    # type checking
    - name: Run type checker
      run: uv run mypy vessim

    # linting
    - name: Run linter
      run: uv run ruff check vessim

    # unit-testing
    - name: Run tests
      run: uv run pytest
